project_id = "xeliuljgfwjygzdumzyv"

[functions.send-otp]
verify_jwt = false

[functions.resend-webhook]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true